import { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'PUBLIC ROUTES',
	description: 'Generated by create next app',
};

export default function PublicLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return <>{children}</>;
}
